### ISSUE TITLE
'loopback-connector-openapi@latest' is not in the npm registry

### ISSUE THREAD

**Issue by uniconstructor** [strongloop/loopback-connector-openapi#3]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

Unable to install package via npm

### Link to sample repo to reproduce issue (if bug)

(not applicable)

### Expected result

Normal installation via `npm install --save loopback-connector-openapi`

### Actual result (if bug)

```sh
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/loopback-connector-openapi - Not found
22 error 404
23 error 404 'loopback-connector-openapi@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)

```

### Additional information (Node.js version, LoopBack version, etc)

Loobpack 3.25.0
npm 6.9.0

**Comment by raymondfeng** [comment]
Sorry, I didn't realize that it's not published to npm. It should be available now.
