### ISSUE TITLE
When creating two datasources consecutivelly (different opeanpi specs for each), schemas get merged

### ISSUE THREAD

**Issue by freakpol** [strongloop/loopback-connector-openapi#5]
```
var ds = loopback.createDataSource('swagger', {
  connector: 'loopback-connector-openapi',
  spec: 'http://petstore.swagger.io/v2/swagger.json',
});

var ds2  = loopback.createDataSource('swagger', {
  connector: 'loopback-connector-openapi',
  spec: 'http://petstore.swagger.io/v2/swagger2.json',
});
```

When calling this, the two schemas get merged and validation of the schemas fails.
This is due to the fact that in the `spec-resolver.js` file, the `const parser = new SwaggerParser();` is called only once. Consider moving this inside each function.

**Comment by raymondfeng** [comment]
@freakpol Would you like to contribute a patch?

**Comment by freakpol** [comment]
Sure, any guidelines for the PR?

**Comment by raymondfeng** [comment]
See https://loopback.io/doc/en/contrib/code-contrib-lb2-lb3.html
